import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
 
import { HeaderComponent } from './header/header.component';
import { HomeComponent } from './home/home.component';
import { MenComponent } from './men/men.component';
import { WomenComponent } from './women/women.component';
import { SearchComponent } from './search/search.component';
import { LoginComponent } from './login/login.component';
import { WishlistComponent } from './wishlist/wishlist.component';
import { BagComponent } from './bag/bag.component';
import { AccessoriesComponent } from './men/categories/accessories/accessories.component';
import { BeltsComponent } from './men/categories/accessories/belts/belts.component';
import { BlanketsComponent } from './men/categories/accessories/blankets/blankets.component';
import { EyewearComponent } from './men/categories/accessories/eyewear/eyewear.component';
import { GlovesComponent } from './men/categories/accessories/gloves/gloves.component';
import { HatsComponent } from './men/categories/accessories/hats/hats.component';
import { JewelryComponent } from './men/categories/accessories/jewelry/jewelry.component';
import { KeychainsComponent } from './men/categories/accessories/keychains/keychains.component';
import { PocketComponent } from './men/categories/accessories/pocket/pocket.component';
import { ScarvesComponent } from './men/categories/accessories/scarves/scarves.component';
import { SocksComponent } from './men/categories/accessories/socks/socks.component';
import { TechComponent } from './men/categories/accessories/tech/tech.component';
import { TiesComponent } from './men/categories/accessories/ties/ties.component';
import { TowelsComponent } from './men/categories/accessories/towels/towels.component';
import { UmbrellasComponent } from './men/categories/accessories/umbrellas/umbrellas.component';
import { WalletsComponent } from './men/categories/accessories/wallets/wallets.component';
import { WatchesComponent } from './men/categories/accessories/watches/watches.component';
import { BagsComponent } from './men/categories/bags/bags.component';
import { BackpacksComponent } from './men/categories/bags/backpacks/backpacks.component';
import { BriefcasesComponent } from './men/categories/bags/briefcases/briefcases.component';
import { DuffleComponent } from './men/categories/bags/duffle/duffle.component';
import { MessengerComponent } from './men/categories/bags/messenger/messenger.component';
import { PouchesComponent } from './men/categories/bags/pouches/pouches.component';
import { ToteComponent } from './men/categories/bags/tote/tote.component';
import { TravelComponent } from './men/categories/bags/travel/travel.component';
import { ClothingComponent } from './men/categories/clothing/clothing.component';
import { JacketsComponent } from './men/categories/clothing/jackets/jackets.component';
import { JeansComponent } from './men/categories/clothing/jeans/jeans.component';
import { PantsComponent } from './men/categories/clothing/pants/pants.component';
import { ShirtsComponent } from './men/categories/clothing/shirts/shirts.component';
import { ShortsComponent } from './men/categories/clothing/shorts/shorts.component';
import { SuitsComponent } from './men/categories/clothing/suits/suits.component';
import { SweatersComponent } from './men/categories/clothing/sweaters/sweaters.component';
import { SwimwearComponent } from './men/categories/clothing/swimwear/swimwear.component';
import { TopsComponent } from './men/categories/clothing/tops/tops.component';
import { UnderwearComponent } from './men/categories/clothing/underwear/underwear.component';
import { ShoesComponent } from './men/categories/shoes/shoes.component';
import { BoatComponent } from './men/categories/shoes/boat/boat.component';
import { BootsComponent } from './men/categories/shoes/boots/boots.component';
import { EspadrillesComponent } from './men/categories/shoes/espadrilles/espadrilles.component';
import { LaceComponent } from './men/categories/shoes/lace/lace.component';
import { LoafersComponent } from './men/categories/shoes/loafers/loafers.component';
import { MonkstrapsComponent } from './men/categories/shoes/monkstraps/monkstraps.component';
import { SandalsComponent } from './men/categories/shoes/sandals/sandals.component';
import { SneakersComponent } from './men/categories/shoes/sneakers/sneakers.component';
import { CategoriesComponent } from './men/categories/categories.component';
import { AccountComponent } from './account/account.component';
import { EmailComponent } from './email/email.component';
import { OrderComponent } from './order/order.component';
import { AddressesComponent } from './addresses/addresses.component';
import { DetailsComponent } from './men/categories/details/details.component';
import { GlassesComponent } from './men/categories/accessories/eyewear/glasses/glasses.component';
import { SunglassesComponent } from './men/categories/accessories/eyewear/sunglasses/sunglasses.component';
import { BeaniesComponent } from './men/categories/accessories/hats/beanies/beanies.component';
import { CapsComponent } from './men/categories/accessories/hats/caps/caps.component';
import { StructuredHatsComponent } from './men/categories/accessories/hats/structured-hats/structured-hats.component';
import { BraceletsComponent } from './men/categories/accessories/jewelry/bracelets/bracelets.component';
import { CufflinksComponent } from './men/categories/accessories/jewelry/cufflinks/cufflinks.component';
import { EarringsComponent } from './men/categories/accessories/jewelry/earrings/earrings.component';
import { NecklacesComponent } from './men/categories/accessories/jewelry/necklaces/necklaces.component';
import { PinsComponent } from './men/categories/accessories/jewelry/pins/pins.component';
import { RingsComponent } from './men/categories/accessories/jewelry/rings/rings.component';
import { HeadphonesComponent } from './men/categories/accessories/tech/headphones/headphones.component';
import { IphoneCasesComponent } from './men/categories/accessories/tech/iphone-cases/iphone-cases.component';
import { BowComponent } from './men/categories/accessories/ties/bow/bow.component';
import { NeckComponent } from './men/categories/accessories/ties/neck/neck.component';
import { CardHoldersComponent } from './men/categories/accessories/wallets/card-holders/card-holders.component';
import { MoneyClipsComponent } from './men/categories/accessories/wallets/money-clips/money-clips.component';
import { PassportHoldersComponent } from './men/categories/accessories/wallets/passport-holders/passport-holders.component';
import { BombersComponent } from './men/categories/clothing/jackets/bombers/bombers.component';
import { CoatsComponent } from './men/categories/clothing/jackets/coats/coats.component';
import { DenimJacketsComponent } from './men/categories/clothing/jackets/denim-jackets/denim-jackets.component';
import { DownComponent } from './men/categories/clothing/jackets/down/down.component';
import { FurComponent } from './men/categories/clothing/jackets/fur/fur.component';
import { JacketsCoatsComponent } from './men/categories/clothing/jackets/jackets-coats/jackets-coats.component';
import { LeatherJacketsComponent } from './men/categories/clothing/jackets/leather-jackets/leather-jackets.component';
import { PeacoatsComponent } from './men/categories/clothing/jackets/peacoats/peacoats.component';
import { TrenchCoatsComponent } from './men/categories/clothing/jackets/trench-coats/trench-coats.component';
import { VestsComponent } from './men/categories/clothing/jackets/vests/vests.component';
import { CargoPantsComponent } from './men/categories/clothing/pants/cargo-pants/cargo-pants.component';
import { LeatherPantsComponent } from './men/categories/clothing/pants/leather-pants/leather-pants.component';
import { SweatpantsComponent } from './men/categories/clothing/pants/sweatpants/sweatpants.component';
import { TrousersComponent } from './men/categories/clothing/pants/trousers/trousers.component';
import { BlazersComponent } from './men/categories/clothing/suits/blazers/blazers.component';
import { SuitsBlazersComponent } from './men/categories/clothing/suits/suits-blazers/suits-blazers.component';
import { TuxedosComponent } from './men/categories/clothing/suits/tuxedos/tuxedos.component';
import { WaistcoatsComponent } from './men/categories/clothing/suits/waistcoats/waistcoats.component';
import { CardigansComponent } from './men/categories/clothing/sweaters/cardigans/cardigans.component';
import { CrewnecksComponent } from './men/categories/clothing/sweaters/crewnecks/crewnecks.component';
import { HoodiesComponent } from './men/categories/clothing/sweaters/hoodies/hoodies.component';
import { SweatshirtsComponent } from './men/categories/clothing/sweaters/sweatshirts/sweatshirts.component';
import { TurtlenecksComponent } from './men/categories/clothing/sweaters/turtlenecks/turtlenecks.component';
import { VNecksComponent } from './men/categories/clothing/sweaters/v-necks/v-necks.component';
import { SwimsuitsComponent } from './men/categories/clothing/swimwear/swimsuits/swimsuits.component';
import { HenleysComponent } from './men/categories/clothing/tops/henleys/henleys.component';
import { PolosComponent } from './men/categories/clothing/tops/polos/polos.component';
import { TShirtsComponent } from './men/categories/clothing/tops/t-shirts/t-shirts.component';
import { TankTopsComponent } from './men/categories/clothing/tops/tank-tops/tank-tops.component';
import { BoxersComponent } from './men/categories/clothing/underwear/boxers/boxers.component';
import { BriefsComponent } from './men/categories/clothing/underwear/briefs/briefs.component';
import { PyjamasComponent } from './men/categories/clothing/underwear/pyjamas/pyjamas.component';
import { RobesComponent } from './men/categories/clothing/underwear/robes/robes.component';
import { BikerComponent } from './men/categories/shoes/boots/biker/biker.component';
import { ChelseaComponent } from './men/categories/shoes/boots/chelsea/chelsea.component';
import { DesertComponent } from './men/categories/shoes/boots/desert/desert.component';
import { LaceUpComponent } from './men/categories/shoes/boots/lace-up/lace-up.component';
import { WingtipComponent } from './men/categories/shoes/boots/wingtip/wingtip.component';
import { ZipupComponent } from './men/categories/shoes/boots/zipup/zipup.component';
import { FlipFlopsComponent } from './men/categories/shoes/sandals/flip-flops/flip-flops.component';
import { HighTopSneakersComponent } from './men/categories/shoes/sneakers/high-top-sneakers/high-top-sneakers.component';
import { LowTopSneakersComponent } from './men/categories/shoes/sneakers/low-top-sneakers/low-top-sneakers.component';

 
const routes: Routes = [
            { path: '', redirectTo: '/home', pathMatch: 'full' },
            { path: 'header', component: HeaderComponent },
            { path: 'home', component: HomeComponent },
            { path: 'men', component: MenComponent },
            { path: 'men', component: CategoriesComponent },
            { path: 'men/accessories', component: AccessoriesComponent },
              { path: 'men/accessories/belts', component: BeltsComponent },
              { path: 'men/accessories/blankets', component: BlanketsComponent },
              { path: 'men/accessories/eyewear', component: EyewearComponent },
                { path: 'men/accessories/eyewear/glasses', component: GlassesComponent },
                { path: 'men/accessories/eyewear/sunglasses', component: SunglassesComponent },
              { path: 'men/accessories/gloves', component: GlovesComponent },
              { path: 'men/accessories/hats', component: HatsComponent },
                { path: 'men/accessories/hats/beanies', component: BeaniesComponent },
                { path: 'men/accessories/hats/caps', component: CapsComponent },
                { path: 'men/accessories/hats/structured-hats', component: StructuredHatsComponent },
              { path: 'men/accessories/jewelry', component: JewelryComponent },
                { path: 'men/accessories/jewelry/bracelets', component: BraceletsComponent },
                { path: 'men/accessories/jewelry/cufflinks', component: CufflinksComponent },
                { path: 'men/accessories/jewelry/earrings', component: EarringsComponent },
                { path: 'men/accessories/jewelry/necklaces', component: NecklacesComponent },
                { path: 'men/accessories/jewelry/pins', component: PinsComponent },
                { path: 'men/accessories/jewelry/rings', component: RingsComponent },
              { path: 'men/accessories/keychains', component: KeychainsComponent },
              { path: 'men/accessories/pocket', component: PocketComponent },
              { path: 'men/accessories/scarves', component: ScarvesComponent },
              { path: 'men/accessories/socks', component: SocksComponent },
              { path: 'men/accessories/tech', component: TechComponent },
                { path: 'men/accessories/tech/headphones', component: HeadphonesComponent },
                { path: 'men/accessories/tech/iphone-cases', component: IphoneCasesComponent },
              { path: 'men/accessories/ties', component: TiesComponent },
                { path: 'men/accessories/ties/bow', component: BowComponent },
                { path: 'men/accessories/ties/neck', component: NeckComponent },
              { path: 'men/accessories/towels', component: TowelsComponent },
              { path: 'men/accessories/umbrellas', component: UmbrellasComponent },
              { path: 'men/accessories/wallets', component: WalletsComponent },
                { path: 'men/accessories/wallets/card-holders', component: CardHoldersComponent },
                { path: 'men/accessories/wallets/money-clips', component: MoneyClipsComponent },
                { path: 'men/accessories/wallets/passport-holders', component: PassportHoldersComponent },
              { path: 'men/accessories/watches', component: WatchesComponent },
          { path: 'men/bags', component: BagsComponent },
              { path: 'men/bags/backpacks', component: BackpacksComponent },
              { path: 'men/bags/briefcases', component: BriefcasesComponent },
              { path: 'men/bags/duffle', component: DuffleComponent },
              { path: 'men/bags/messenger', component: MessengerComponent },
              { path: 'men/bags/pouches', component: PouchesComponent },
              { path: 'men/bags/tote', component: ToteComponent },
              { path: 'men/bags/travel', component: TravelComponent },
          { path: 'men/clothing', component: ClothingComponent},
          { path: 'men/clothing/jackets', component: JacketsComponent },
                { path: 'men/clothing/jackets/bombers', component: BombersComponent },
                { path: 'men/clothing/jackets/coats', component: CoatsComponent },
                { path: 'men/clothing/jackets/denim-jackets', component: DenimJacketsComponent },
                { path: 'men/clothing/jackets/down', component: DownComponent },
                { path: 'men/clothing/jackets/fur', component: FurComponent },
                { path: 'men/clothing/jackets/jackets-coat', component: JacketsCoatsComponent },
                { path: 'men/clothing/jackets/leather-jackets', component: LeatherJacketsComponent },
                { path: 'men/clothing/jackets/peacoats', component: PeacoatsComponent },
                { path: 'men/clothing/jackets/trench-coats', component: TrenchCoatsComponent },
                { path: 'men/clothing/jackets/vests', component: VestsComponent },
              { path: 'men/clothing/jeans', component: JeansComponent },
              { path: 'men/clothing/pants', component: PantsComponent },
                { path: 'men/clothing/pants/cargo-pants', component: CargoPantsComponent },
                { path: 'men/clothing/pants/leather-pants', component: LeatherPantsComponent },
                { path: 'men/clothing/pants/sweatpants', component: SweatpantsComponent },
                { path: 'men/clothing/pants/trousers', component: TrousersComponent },
              { path: 'men/clothing/shirts', component: ShirtsComponent },
              { path: 'men/clothing/shorts', component: ShortsComponent },
              { path: 'men/clothing/suits', component: SuitsComponent },
                { path: 'men/clothing/suits/blazers', component: BlazersComponent },
                { path: 'men/clothing/suits/suits-blazers', component: SuitsBlazersComponent },
                { path: 'men/clothing/suits/tuxedos', component: TuxedosComponent },
                { path: 'men/clothing/suits/waistcoats', component: WaistcoatsComponent },
              { path: 'men/clothing/sweaters', component: SweatersComponent },
                { path: 'men/clothing/sweaters/cardigans', component: CardigansComponent },
                { path: 'men/clothing/sweaters/crewnecks', component: CrewnecksComponent },
                { path: 'men/clothing/sweaters/hoodies', component: HoodiesComponent },
                { path: 'men/clothing/sweaters/sweatshirts', component: SweatshirtsComponent },
                { path: 'men/clothing/sweaters/turtlenecks', component: TurtlenecksComponent },
                { path: 'men/clothing/sweaters/sweater/v-necks', component: VNecksComponent },
              { path: 'men/clothing/swimwear', component: SwimwearComponent },
                { path: 'men/clothing/swimwear/swimsuits', component: SwimsuitsComponent },  
              { path: 'men/clothing/tops', component: TopsComponent },
                { path: 'men/clothing/tops/henleys', component: HenleysComponent },
                { path: 'men/clothing/tops/polos', component: PolosComponent },
                { path: 'men/clothing/tops/t-shirts', component: TShirtsComponent },
                { path: 'men/clothing/tops/tank-tops', component: TankTopsComponent },
              { path: 'men/clothing/underwear', component: UnderwearComponent },
                { path: 'men/clothing/underwear/boxers', component: BoxersComponent },
                { path: 'men/clothing/underwear/briefs', component: BriefsComponent },
                { path: 'men/clothing/underwear/pyjamas', component: PyjamasComponent },
                { path: 'men/clothing/underwear/robes', component: RobesComponent },
          { path: 'men/shoes', component: ShoesComponent },
              { path: 'men/shoes/boat', component: BoatComponent },
              { path: 'men/shoes/boots', component: BootsComponent },
                { path: 'men/shoes/boots/biker', component: BikerComponent },
                { path: 'men/shoes/boots/chelsea', component: ChelseaComponent },
                { path: 'men/shoes/boots/desert', component: DesertComponent },
                { path: 'men/shoes/boots/lace-up', component: LaceUpComponent },
                { path: 'men/shoes/wingtip', component: WingtipComponent },
                { path: 'men/shoes/boots/zipup', component: ZipupComponent },
              { path: 'men/shoes/espadrilles', component: EspadrillesComponent },
              { path: 'men/shoes/lace', component: LaceComponent },
              { path: 'men/shoes/loafers', component: LoafersComponent },
              { path: 'men/shoes/monkstraps', component: MonkstrapsComponent },
              { path: 'men/shoes/sandals', component: SandalsComponent },
                { path: 'men/shoes/sandals/flip-flops', component: FlipFlopsComponent },
              { path: 'men/shoes/sneakers', component: SneakersComponent },
                { path: 'men/shoes/sneakers/high-top-sneakers', component: HighTopSneakersComponent },
                { path: 'men/shoes/sneakers/low-top-sneakers', component: LowTopSneakersComponent },
              { path: 'men/details', component: DetailsComponent },
          { path: 'women', component: WomenComponent },
          { path: 'search', component: SearchComponent },
          { path: 'login', component: LoginComponent },
          { path: 'email', component: EmailComponent },
          { path: 'order', component: OrderComponent },
          { path: 'addresses', component: AddressesComponent },
          { path: 'wishlist', component: WishlistComponent },
          { path: 'bag', component: BagComponent },
          { path: 'account', component: AccountComponent }
        ];
 
@NgModule({
  imports: [ RouterModule.forRoot(routes) ],
  exports: [ RouterModule ]
})
export class AppRoutingModule {}
